In [55]:
import pandas as pd
import h5py, json

In [143]:
infile = 's5-series_json.dir/GSE71585-GPL13112.json'

In [144]:
# Get dataset json
with open(infile) as openfile:
    dataset = json.loads(openfile.read())

# Get dataset accession
dataset_accession = os.path.basename(infile).split('-')[0]

In [145]:
from sqlalchemy import create_engine, MetaData
import pymysql
pymysql.install_as_MySQLdb()
from sqlalchemy.orm import sessionmaker

In [146]:
engine = create_engine(os.environ['SQLALCHEMY_DATABASE_URI']+'-dev?charset=utf8')
Session = sessionmaker(bind=engine)
metadata = MetaData()
metadata.reflect(bind=engine)
tables = metadata.tables

In [100]:
def upload_data(data, keys, table):

    return engine.execute(tables[table].insert({x: data[x] for x in keys}))

In [101]:
a = upload_data(data=dataset, keys=['title', 'summary', 'date', 'accession'], table='dataset')
a

In [116]:
engine.execute(tables['platform'].select().where(tables['platform'].columns['gpl'] == 'GPL13112')).fetchall()[0]['id']

1

In [104]:
a.lastrowid

4

In [147]:

# Create sample dataframe
sample_dataframe = pd.DataFrame(dataset['samples']).T.reset_index().rename(columns={'index': 'accession', 'Sample Title': 'title'})[['accession', 'title']]

# Add foreign keys
sample_dataframe['dataset_fk'] = dataset['dataset_id']
sample_dataframe['platform_fk'] = dataset['platform_id']

# Append
sample_dataframe.to_sql('sample_new', if_exists='append')

KeyError: 'dataset_id'

In [152]:
dataset['sample_ids'] = pd.DataFrame(engine.execute(tables['sample_new'].select()).fetchall()).rename(columns={0: 'sample_fk', 1: 'accession'})[['sample_fk', 'accession']]
dataset['sample_ids']

     sample_fk   accession
0            1  GSM1839194
1            2  GSM1839202
2            3  GSM1839262
3            4  GSM1839263
4            5  GSM1839264
5            6  GSM1839265
6            7  GSM1839266
7            8  GSM1839267
8            9  GSM1839268
9           10  GSM1839269
10          11  GSM1839270
11          12  GSM1839271
12          13  GSM1839272
13          14  GSM1839273
14          15  GSM1839274
15          16  GSM1839279
16          17  GSM1839290
17          18  GSM1839292
18          19  GSM1839293
19          20  GSM1839297
20          21  GSM1839299
21          22  GSM1839301
22          23  GSM1839302
23          24  GSM1839308
24          25  GSM1839316
25          26  GSM1839325
26          27  GSM1839326
27          28  GSM1839327
28          29  GSM1839328
29          30  GSM1839329
..         ...         ...
610        611  GSM1922376
611        612  GSM1922377
612        613  GSM1922378
613        614  GSM1922379
614        615  GSM1922380
615        616  GSM1922381
616        617  GSM1922382
617        618  GSM1922383
618        619  GSM1922384
619        620  GSM1922385
620        621  GSM1922386
621        622  GSM2277105
622        623  GSM2277106
623        624  GSM2277107
624        625  GSM2277108
625        626  GSM2277109
626        627  GSM2277110
627        628  GSM2277111
628        629  GSM2277112
629        630  GSM2277113
630        631  GSM2277114
631        632  GSM2337232
632        633  GSM2337233
633        634  GSM2337234
634        635  GSM2337235
635        636  GSM2337236
636        637  GSM2337237
637        638  GSM2337238
638        639  GSM2337239
639        640  GSM2337240

[640 rows x 2 columns]

In [150]:
pd.melt(pd.DataFrame(dataset['samples']).T.reset_index(), id_vars='index').merge(dataset['sample_ids'], left_on='index', right_on='accession')

           index      variable                      value
0     GSM1839192  Sample Title   Calb2_tdTpositive_cell_1
1     GSM1839193  Sample Title   Calb2_tdTpositive_cell_2
2     GSM1839195  Sample Title   Calb2_tdTpositive_cell_4
3     GSM1839196  Sample Title   Calb2_tdTpositive_cell_5
4     GSM1839197  Sample Title   Calb2_tdTpositive_cell_6
5     GSM1839198  Sample Title   Calb2_tdTpositive_cell_7
6     GSM1839199  Sample Title   Calb2_tdTpositive_cell_8
7     GSM1839200  Sample Title   Calb2_tdTpositive_cell_9
8     GSM1839201  Sample Title  Calb2_tdTpositive_cell_10
9     GSM1839203  Sample Title  Calb2_tdTpositive_cell_12
10    GSM1839204  Sample Title  Calb2_tdTpositive_cell_13
11    GSM1839205  Sample Title  Calb2_tdTpositive_cell_14
12    GSM1839206  Sample Title  Calb2_tdTpositive_cell_15
13    GSM1839207  Sample Title  Calb2_tdTpositive_cell_16
14    GSM1839208  Sample Title  Calb2_tdTpositive_cell_17
15    GSM1839209  Sample Title  Calb2_tdTpositive_cell_18
16    GSM1839210  Sample Title  Calb2_tdTpositive_cell_19
17    GSM1839211  Sample Title  Calb2_tdTpositive_cell_20
18    GSM1839212  Sample Title  Calb2_tdTpositive_cell_21
19    GSM1839213  Sample Title  Calb2_tdTpositive_cell_22
20    GSM1839214  Sample Title  Calb2_tdTpositive_cell_23
21    GSM1839215  Sample Title  Calb2_tdTpositive_cell_24
22    GSM1839216  Sample Title  Calb2_tdTpositive_cell_25
23    GSM1839217  Sample Title  Calb2_tdTpositive_cell_26
24    GSM1839218  Sample Title  Calb2_tdTpositive_cell_27
25    GSM1839219  Sample Title  Calb2_tdTpositive_cell_28
26    GSM1839220  Sample Title  Calb2_tdTpositive_cell_29
27    GSM1839221  Sample Title  Calb2_tdTpositive_cell_30
28    GSM1839222  Sample Title  Calb2_tdTpositive_cell_31
29    GSM1839223  Sample Title  Calb2_tdTpositive_cell_32
...          ...           ...                        ...
7642  GSM1840875      reporter             RCL-tdT (Ai14)
7643  GSM1840877      reporter             RCL-tdT (Ai14)
7644  GSM1840878      reporter             RCL-tdT (Ai14)
7645  GSM1840879      reporter             RCL-tdT (Ai14)
7646  GSM1840880      reporter             RCL-tdT (Ai14)
7647  GSM1840881      reporter             RCL-tdT (Ai14)
7648  GSM1840882      reporter             RCL-tdT (Ai14)
7649  GSM1840883      reporter             RCL-tdT (Ai14)
7650  GSM1840885      reporter             RCL-tdT (Ai14)
7651  GSM1840886      reporter             RCL-tdT (Ai14)
7652  GSM1840887      reporter             RCL-tdT (Ai14)
7653  GSM1840888      reporter             RCL-tdT (Ai14)
7654  GSM1840889      reporter             RCL-tdT (Ai14)
7655  GSM1840890      reporter             RCL-tdT (Ai14)
7656  GSM1840891      reporter             RCL-tdT (Ai14)
7657  GSM1840892      reporter             RCL-tdT (Ai14)
7658  GSM1840894      reporter             RCL-tdT (Ai14)
7659  GSM1840896      reporter             RCL-tdT (Ai14)
7660  GSM1840899      reporter             RCL-tdT (Ai14)
7661  GSM1840900      reporter             RCL-tdT (Ai14)
7662  GSM1840902      reporter             RCL-tdT (Ai14)
7663  GSM1840904      reporter             RCL-tdT (Ai14)
7664  GSM1840930      reporter             RCL-tdT (Ai14)
7665  GSM1840987      reporter             RCL-tdT (Ai14)
7666  GSM1840988      reporter             RCL-tdT (Ai14)
7667  GSM1840989      reporter             RCL-tdT (Ai14)
7668  GSM1840991      reporter             RCL-tdT (Ai14)
7669  GSM1840998      reporter                    RCL-tdT
7670  GSM1840999      reporter                    RCL-tdT
7671  GSM1841000      reporter          Snap25-LSL-2A-GFP

[7672 rows x 3 columns]